import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { ExtensionContext } from 'vscode';
import { state } from './vscode-stub';
import { activate } from '../src/extension';
import { binaryRelativePath } from '../src/launcher';

test('用户切换链路：不自动接管、拒绝无效配置、备份旧路径、切换后待重载、恢复默认', async t => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'codex-extension-'));
  t.after(() => fs.rm(dir, { recursive: true, force: true }));
  const home = path.join(dir, 'home'); const storage = path.join(dir, 'storage');
  await fs.mkdir(home);
  await fs.writeFile(path.join(home, 'good.config.toml'), 'model_provider = "relay"');
  await fs.writeFile(path.join(home, 'broken.config.toml'), '[incomplete');
  const base = 'model = "untouched"\n'; await fs.writeFile(path.join(home, 'config.toml'), base);
  state.extensionPath = path.join(dir, 'openai.chatgpt-test');
  const binary = path.join(state.extensionPath, binaryRelativePath());
  await fs.mkdir(path.dirname(binary), { recursive: true }); await fs.writeFile(binary, '#!/bin/sh\n', { mode: 0o700 });
  state.values.set('codexProfiles.codexHome', home);
  state.values.set('chatgpt.cliExecutable', '/previous/startup');
  await activate({ globalStorageUri: { fsPath: storage }, asAbsolutePath: (file: string) => path.resolve(file), subscriptions: [] } as unknown as ExtensionContext);
  assert.equal(state.updates.length, 0);
  state.choice = 'broken'; await state.commands.get('codexProfiles.switch')!();
  assert.equal(state.updates.length, 0);
  state.choice = 'good'; await state.commands.get('codexProfiles.switch')!();
  assert.equal(state.updates.length, 1);
  assert.match(state.status.text, /good · 待重载/);
  assert.equal(JSON.parse(await fs.readFile(path.join(storage, 'previous-startup.json'), 'utf8')).cliExecutable, '/previous/startup');
  await state.commands.get('codexProfiles.reset')!();
  assert.equal(state.values.get('chatgpt.cliExecutable'), undefined);
  assert.equal(await fs.readFile(path.join(home, 'config.toml'), 'utf8'), base);
});
